# Generated by Django 5.0.4 on 2024-05-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=300)),
                ('job', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('fb_profile', models.CharField(max_length=30)),
                ('inst_profile', models.CharField(max_length=30)),
                ('link_profile', models.CharField(max_length=30)),
                ('tw_profile', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
