# Generated by Django 5.0.4 on 2024-05-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
