# Generated by Django 5.0.4 on 2024-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_userinfo_company_alter_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='image'),
        ),
    ]
